version: '3.2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/conf.d/cache.conf:/etc/nginx/conf.d/cache.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/vhost.d/host:/etc/nginx/vhost.d/${HOST}
      - ./nginx/vhost.d/host_location:/etc/nginx/vhost.d/${HOST}_location
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - dhparam:/etc/nginx/dhparam
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
  letsencrypt:
    depends_on:
      - nginx-proxy
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - dhparam:/etc/nginx/dhparam:ro
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
  ghost:
    environment:
      - LETSENCRYPT_HOST=${HOST}
      - LETSENCRYPT_EMAIL
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PORT=2368
    user: 0:1000
volumes:
  certs:
  dhparam:
  html:
  vhost:
