kind: Deployment
apiVersion: apps/v1
metadata:
  name: ghost
spec:
  selector:
    matchLabels:
      app: ghost
  template:
    spec:
      containers:
      - name: ghost
        image: ghost:3.42.6-alpine
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 2368
